{% set version = "isis4.4.0" %} # synched up to isis dependencies for this version
package:
    name: gdal
    version: {{ version }}

source:
    fn: gdal-2.0.2.tar.gz
    url: http://download.osgeo.org/gdal/2.0.2/gdal-2.0.2.tar.gz
    md5: 573865f3f59ba7b4f8f4cddf223b52a5
    patches:
#        - clang.patch  # [osx]
#        - prepend-dll.patch  # [win]

build:
    number: 0

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - curl 7.64.0
        - libcurl 7.64.0
        - geos 3.7.3
        - jpeg 9b
        - openjpeg 2.1.0
        - krb5 1.16.3
        - libedit
        - libpng 1.6.37
        - libssh2 1.8.0
        - libtiff 4.0.9
        - ncurses 6.2
        - openssl 1.0.2u
        - proj4 4.9.3
        - tk 8.6.10
        - xz 5.2.5
        - zlib 1.2.11
        - isis   4.4.0 # to catch dependency problems
    run:
        - curl 7.64.0
        - libcurl 7.64.0
        - geos 3.7.3
        - jpeg 9b
        - openjpeg 2.1.0
        - krb5 1.16.3
        - libedit
        - libpng 1.6.37
        - libssh2 1.8.0
        - libtiff 4.0.9
        - ncurses 6.2
        - openssl 1.0.2u
        - proj4 4.9.3
        - tk 8.6.10
        - xz 5.2.5
        - zlib 1.2.11
        - isis   4.4.0 # to catch dependency problems

test:

about:
    home: http://www.gdal.org/
    license: MIT
    summary: The Geospatial Data Abstraction Library (GDAL)

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
