{% set version = "2.0.2" %}
package:
    name: gdal
    version: {{ version }}

source:
    fn: gdal-{{ version }}.tar.gz
    url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.gz
    md5: 573865f3f59ba7b4f8f4cddf223b52a5
    patches:
        - clang.patch  # [osx]
        - prepend-dll.patch  # [win]
        - install_scripts.patch

build:
    number: 0

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - jpeg
        - libpng
        - libtiff
        - openjpeg                  2.1
        - xz
        - zlib
        - curl
        - libcurl
        - geos
        - krb5
        - libedit
        - libgcc-ng
        - libssh2
        - libstdcxx-ng
        - ncurses
        - openssl
        - proj4                     4.9.3
        - tk
        - imagemagick               6.8.6
    run:
        - jpeg
        - libpng
        - libtiff
        - openjpeg                  2.1
        - xz
        - zlib
        - curl
        - libcurl
        - geos
        - krb5
        - libedit
        - libgcc-ng
        - libssh2
        - libstdcxx-ng
        - ncurses
        - openssl
        - proj4                     4.9.3
        - tk

test:
    files:
        imports:
        commands:
        - gdal_translate --version  # [not win]
        - gdalwarp --version  # [not win]
        - gdalinfo --formats  # [not win]

about:
    home: http://www.gdal.org/
    license: MIT
    summary: The Geospatial Data Abstraction Library (GDAL)

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
