{% set version = "2.0.2" %}
package:
    name: gdal
    version: {{ version }}

source:
    fn: gdal-{{ version }}.tar.gz
    url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.gz
    md5: 573865f3f59ba7b4f8f4cddf223b52a5
    patches:
        - clang.patch  # [osx]
        - prepend-dll.patch  # [win]
        - install_scripts.patch

build:
    number: 0

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - curl                      7.63.0
        - libcurl                   7.63.0
        - geos                      3.7.3
        - jpeg                      9b
        - openjpeg                  2.1.0
        - krb5                      1.16.3
        - libedit                   3.1.20181209
        - libgcc-ng                 9.1.0
        - libpng                    1.6.37
        - libssh2                   1.8.0
        - libstdcxx-ng              9.1.0
        - libtiff                   4.0.9
        - ncurses                   6.1
        - openjpeg                  2.1.0
        - openssl                   1.0.2u
        - proj4                     4.9.3
        - tk                        8.6.10
        - xz                        5.2.5
        - zlib                      1.2.11

    run:
        - curl                      7.63.0
        - libcurl                   7.63.0
        - geos                      3.7.3
        - jpeg                      9b
        - openjpeg                  2.1.0
        - krb5                      1.16.3
        - libedit                   3.1.20181209
        - libgcc-ng                 9.1.0
        - libpng                    1.6.37
        - libssh2                   1.8.0
        - libstdcxx-ng              9.1.0
        - libtiff                   4.0.9
        - ncurses                   6.1
        - openjpeg                  2.1.0
        - openssl                   1.0.2u
        - proj4                     4.9.3
        - tk                        8.6.10
        - xz                        5.2.5
        - zlib                      1.2.11

test:
    files:
        imports:
        commands:
        - gdal_translate --version  # [not win]
        - gdalwarp --version  # [not win]
        - gdalinfo --formats  # [not win]

about:
    home: http://www.gdal.org/
    license: MIT
    summary: The Geospatial Data Abstraction Library (GDAL)

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
